### ISSUE TITLE
Update windows setup

### ISSUE THREAD

**Issue by ann0see** [diegodlh/jamulus-es#4]
I've made some changes to the windows setup (english wiki) which should be translated.

**Comment by ann0see** [comment]
@ignotus666 and others: also the privacy site has been updated to describe that constants should be changed if you don't want to use google. Now there's no more direct line number link. I hope your script mentioned the changes.

**Comment by ignotus666** [comment]
Don't worry, if no one else does I'll update the Spanish wiki after the weekend. I get notifications whenever anything changes via an RSS feed and can see what they are in OmegaT.

**Comment by ann0see** [comment]
Ok. So it seems to be all ok.
