### ISSUE TITLE
Move files over to jamulus.io

### ISSUE THREAD

**Issue by ann0see** [diegodlh/jamulus-es#5]
Because of various reasons including that google doesn't index the jamulus wiki, the new wiki will be accessible under jamulus.io

The repo for that is https://github.com/jamulussoftware/jamulussoftware.github.io

It would be great if you moved the wiki over too.

**Comment by ignotus666** [comment]
Hi, I've been very busy with work lately but when I get the chance I'll look into moving over the files and updating them.

**Comment by ann0see** [comment]
Ok. No problem. You can take your time. I've already added you as translator, but you you will have to open a PR.

**Comment by diegodlh** [comment]
Great news! I've been rather busy and disconnected as well. Thank you @ignotus666 for taking care of this

**Comment by ann0see** [comment]
@diegodlh I've invited you to the jamulussoftware organisation as a translator.

**Comment by ignotus666** [comment]
Hi @diegodlh , just to let you know that all the content has been moved over to the new wiki and updated - so if you want you can give the people on the Facebook page the new address.

**Comment by ann0see** [comment]
Can we close this now?

**Comment by ignotus666** [comment]
I'd let Diego do that in case he hasn't read it yet.

**Comment by diegodlh** [comment]
I'm really sorry for the delay! I've just added a link on all of this repo's wiki pages to their corresponding jamulus.io wiki page. Thank you both for your work! Closing now

**Comment by ann0see** [comment]
No problem;-)
